name: test

on:
  workflow_dispatch:                                # manually triggered

jobs:
  CI:

   
   
    # login to Azure account
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}                         # JSON objects which represents service principal

    # blue/green
    - name: swap QA and production slots
      run: |
        az webapp deployment slot swap -n BPCalculator20221210142544 -g appservice-rg --slot development --target-slot production 


