name: build and package

on:
  workflow_dispatch:                                # manually triggered

jobs:
  CI:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Install dependencies
      run: dotnet restore BPCalculator/
    - name: Install dependencies2
      run: dotnet restore XunitTestProject1/

    - name: Build for release
      run: dotnet build BPCalculator/BPCalculator.csproj --configuration Release --no-restore 
      
       # run standard unit tests
    - name: Run Unit Tests
      run: dotnet test XunitTestProject1/XunitTestProject1.csproj  --verbosity normal -l:trx
      
       # run Specflow+ tests
    - name: Run Acceptance Tests 
      run: dotnet test SpecFlowProject_net31/SpecFlowProject_net31.csproj  --verbosity normal -l:trx
      
    - name: Analyze code with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=simonfarrell1981
          -Dsonar.projectKey=SimonFarrell1981_AS1_BPCalculator
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.verbose=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - name: Depcheck
      uses: dependency-check/Dependency-Check_Action@main
      id: Depcheck
      with:
          project: 'BMI'
          path: '.'
          format: 'HTML'    
          args: >
            --failOnCVSS 8            
          # fail if CVSS score (CVE scoring system) is High >=8
          
    - name: Upload Test results
      uses: actions/upload-artifact@master
      with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
           
  CD:                                             
    name: CD
    needs: CI
    environment:
      name: QA
      url: https://bpcalculator20221210142544-development.azurewebsites.net                                 
    runs-on: windows-latest
    env:
      AZURE_WEBAPP_NAME: BPCalculator20221210142544            # set this to your application's name
      AZURE_WEBAPP_PACKAGE_PATH: 'publish'              # set this to the path to your web app project
    steps:
    - uses: actions/checkout@v2

    # publish web app ready for deployment
    - name: Publish web app
      run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp
    
    # Deploy to Azure app service to staging slot using publish profile for staging slot
    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}                            
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}     # Define secret variable in environment
        slot-name: development
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
        # Run Selenium tests
    - name: Run Selenium tests
      run: dotnet test ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp/SeleniumTest.dll /Settings:SeleniumTest.runsettings --logger:"trx;LogFileName=selenium.trx"
  
    # Upload results of selenium tests
    - uses: actions/upload-artifact@v2
      with:
        name: Selenium Tests Results
        path: TestResults/selenium.trx

    # login to Azure account
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}                         # JSON objects which represents service principal

    # blue/green
    - name: swap QA and production slots
      run: |
        az webapp deployment slot swap -n gc-bmicalculator-ga -g gcresourcegroup1 --slot staging --target-slot production 


