name: build and package

on:
  workflow_dispatch:                                # manually triggered

jobs:
  build_package:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Install dependencies
      run: dotnet restore BPCalculator/
    - name: Install dependencies2
      run: dotnet restore XunitTestProject1/

    - name: Build for release
      run: dotnet build BPCalculator/BPCalculator.csproj --configuration Release --no-restore 
      
       # run standard unit tests
    - name: Run Unit Tests
      run: dotnet test XunitTestProject1/XunitTestProject1.csproj  --verbosity normal -l:trx
      
       # run Specflow+ tests
    - name: Run Acceptance Tests 
      run: dotnet test SpecFlowProject_net31/SpecFlowProject_net31.csproj  --verbosity normal -l:trx
      
    - name: Analyze code with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=simonfarrell1981
          -Dsonar.projectKey=SimonFarrell1981_AS1_BPCalculator
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.verbose=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
